<script src="/code/nui/dialog/intro.js"></script>
<script src="/code/nui/dialog/example-modal.js"></script>
<script src="/code/nui/dialog/example-loading.js"></script>

<div class="PageSection SplashSection SplashGraphicNUI"><div>
	<h2>NUI.Dialog</h2>
	<p>A little alert box you can throw content inside of to feature.</p>
	<p style="text-align:center;"><a href="#" class="Button" onclick="return Intro_ShowExampleDialog();">show me</a></p>
	<pre class="CodeBlock"><?php echo $javascript->highlight(file_get_contents(sprintf('%s/www/code/nui/dialog/intro.js',PROJECT_ROOT))) ?></pre>
</div></div>

<div class="PageSection"><div>
	<p>These little dialog widgets are great for having moveable content, alerts, or notifications. If you pack
	them inside of a NUI.Overlay they will demand respect from the user until delt with. They also have a neat
	little feature where you can disable any buttons placed in it and show a loading animation while something
	happens asynchronously in the background.</p>
</div></div>

<div class="PageSection"><div>
	<h2 class="NetherHeader">Constructor</h2>
	<pre class="CodeBlock"><?php echo $javascript->highlight(file_get_contents(sprintf('%s/www/code/nui/dialog/construct.js',PROJECT_ROOT))) ?></pre>
</div></div>

<div class="PageSection"><div>
	<h2 class="NetherHeader">Methods</h2>
	<pre class="CodeBlock"><?php echo $javascript->highlight(file_get_contents(sprintf('%s/www/code/nui/dialog/methods.js',PROJECT_ROOT))) ?></pre>
</div></div>

<div class="PageSection"><div>
	<h2 class="NetherHeader">Example: Modal Dialog</h2>
	<pre class="CodeBlock"><?php echo $javascript->highlight(file_get_contents(sprintf('%s/www/code/nui/dialog/example-modal.js',PROJECT_ROOT))) ?></pre>
	<div class="TextCenter">
		<a href="#" class="Button" onclick="return LocalExampleModalDialog();">click me to see</a>
	</div>
</div></div>

<div class="PageSection"><div>
	<h2 class="NetherHeader">Example: Loading Dialog</h2>
	<pre class="CodeBlock"><?php echo $javascript->highlight(file_get_contents(sprintf('%s/www/code/nui/dialog/example-loading.js',PROJECT_ROOT))) ?></pre>
	<div class="TextCenter">
		<a href="#" class="Button" onclick="return LocalExampleBusyDialog();">click me to see</a>
	</div>
</div></div>
