<?php

$this->Set('page-title','Super Serial Error');
$this->Set('page-subtitle','It has been regarded with the upmost severity.');
$this->Set('page-navigation',[
	new Website\Item([ 'Name'=>'Home', 'URL'=>'/' ]),
	new Website\Item([ 'Name'=>'Error: Does Not Compute' ])
]);

echo (new Website\Block\ContentHeader);
echo (new Website\Block\NavigationBar);

?>

<div class="PageSection"><div>
	<p class="TextCenter"><img src="<?php echo $this->GetThemeURI('gfx/bsg-adama-emo.jpg') ?>" /></p>
</div></div>
