<?php

$route = Nether\Stash::Get('web:route');

?>
<!doctype html>
<html lang="en">
<head>
	<title><?php $surface->Show('page-title') ?></title>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<meta name="viewport" content="width=800" />
	<link rel="shortcut icon" type="image/png" href="<?php $surface->FromTheme('gfx/favicon.png') ?>" />
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway:400,200" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
	<link rel="stylesheet" href="/share/nui/nui.css" />
	<link rel="stylesheet" href="/share/fshl/style.css" />
	<link rel="stylesheet" type="text/css" href="<?php $surface->FromTheme('design.css') ?>" />

	<script src="/share/jquery/jquery.min.js"></script>
	<script src="/share/nui/nui.js"></script>
</head>
<body>

<div id="PageHeader">
	<h1 class="NetherHeader"><a href="/">Nether</a></h1>
	<ul>
		<li class="<?php echo(($route->Name==='home')?('on'):('off')) ?>"><a href="/">Home</a></li>
		<li class="<?php echo(($route->Name==='npf')?('on'):('off')) ?>"><a href="/npf/">NPF</a></li>
		<li class="<?php echo(($route->Name==='nui')?('on'):('off')) ?>"><a href="/nui/">NUI</a></li>
		<!--
		<li><a href="http://github.com/netherphp">Github</a></li>
		<li><a href="https://travis-ci.org/netherphp">Build Status</a></li>
		<li><a href="https://packagist.org/packages/netherphp/">Packagist</a></li>
		-->
	</ul>
</div>

<div id="PageArea">
<?php echo $surface->Get('stdout').PHP_EOL ?>
</div>

<div id="PageFooter"><div>
	<div style="float:right;opacity:0.5;">
		<img src="<?php $surface->FromTheme('gfx/logo-html5.png') ?>" title="HTML5" />
		<img src="<?php $surface->FromTheme('gfx/logo-css3.png') ?>" title="CSS3" />
		<img src="<?php $surface->FromTheme('gfx/logo-rarity.png') ?>" title="The type of pony everypony should know." />
	</div>
	all the things copyright © 2015 nether.io / bob majdak jr<br />
	header image copyright... that one tv show.
</div></div>

<script type="text/javascript">
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-33782644-3', 'auto');
	ga('send', 'pageview');
</script>

</body>
</html>