<?php

$this->Set('page-title','Installing Javascript with Composer');
$this->Set('page-subtitle','How to deploy private assets from Composer into the public space.');
$this->Set('page-navigation',[
	new Website\Item([ 'Name'=>'Home', 'URL'=>'/' ]),
	new Website\Item([ 'Name'=>'Nether PHP Framework', 'URL'=>'/npf/' ]),
	new Website\Item([ 'Name'=>'OneScript', 'URL'=>'/npf/onescript' ]),
	new Website\Item([ 'Name'=>$this->Get('page-title') ])
]);

echo (new Website\Block\ContentHeader);
echo (new Website\Block\NavigationBar);

?>

<div class="PageSection"><div>
	TODO ^_^
</div></div>

