<div class="PageSection SplashSection SplashGraphicNPF"><div>
	<h2>Nether Console</h2>
	<p>Quickly (and easily) craft simple CLI applications for your app.</p>
</div></div>

<div class="PageNavigation">
	<ul class="Breadcrumbs">
		<li><i class="fa fa-home"></i></li>
		<li><a href="/">Home</a></li>
		<li><i class="fa fa-angle-right"></i></li>
		<li><a href="/npf/">Nether PHP Framework</a></li>
	</ul>
</div>

<div class="PageSection"><div>
	TODO ^_^
</div></div>

