
<div class="PageSection SplashSection SplashGraphicNPF"><div>
	<h2>Nether OneScript</h2>
	<p>Optimise your client-side scripting into singular bundles.</p>
</div></div>

<div class="PageSection"><div>
	<h2 class="NetherHeader">A Problem</h2>
	<p>One of the simplest ways to demonstrate the utility of OneScript is with jQuery. Love it or hate it, if you have used it you cannot really deny that it can get pretty messy when you start bolting on third-party extensions to it willy nilly. In a rush we will just start appending more script tags after the original jQuery script, and before we know it we have this large slow messy pile of separate scripts probably killing the mobile browsers.</p>
	<pre class="CodeBlock"><?php echo $javascript->highlight(file_get_contents(sprintf('%s/www/code/npf/onescript/problem.txt',PROJECT_ROOT))) ?></pre>
	<p>This is a problem especally for low power devices for two main reasons.</p>
	<p>First, depending on the resources available to the browser and the configuration of the server, the browser may actually establish multiple socket connections to the server to download the scripts. Establishing connections are much slower than the act of actually downloading small text files.</p>
	<p>Second, because of the first, the browser may have to delay execution until it has all the scripts ready to go. This could give your page the appearance of <em>looking</em> ready to go, even though it is unresponsive until the rest of the scripts finish in the background.</p>
</div></div>

<div class="PageSection"><div>
	<h2 class="NetherHeader">An Answer</h2>
	<p>What if you could just load one script instead? One connection, one process of downloading and script preparation. Not only will the entire page (often) download faster, but it will be responsive faster. The browser may not have to delay execution - meaning your jQuery(document).ready() will execute sooner.</p>
	<pre class="CodeBlock"><?php echo $javascript->highlight(file_get_contents(sprintf('%s/www/code/npf/onescript/answer.txt',PROJECT_ROOT))) ?></pre>
	<p>This is what OneScript helps you do, as well as making it easy to update those compiled scripts later.</p>
</div></div>
