<?php

$this->Set('page-title','Surface');
$this->Set('page-subtitle','A page template and rendering engine.');
$this->Set('page-navigation',[
	new Website\Item([ 'Name'=>'Home', 'URL'=>'/' ]),
	new Website\Item([ 'Name'=>'Nether PHP Framework', 'URL'=>'/npf/' ]),
	new Website\Item([ 'Name'=>$this->Get('page-title') ])
]);

echo (new Website\Block\ContentHeader);
echo (new Website\Block\NavigationBar);

?>

<div class="PageSection"><div>
	TODO ^_^
</div></div>

